name: OhNoez

main: org.selurgniman.bukkit.ohnoez.OhNoez

version: 0.5

database: true

commands:
    ohnoez:
        description: lists the items you dropped at your last death
        usage: /ohnoez [list|credits|claim]
        
permissions:
    ohnoez.*:
        description: OhNoez master permission
        defaulit: false
        children:
            ohnoez.credits.adjust: true
    ohnoez.credits.adjust:
        description: Allows access to credit adjustment commands
        default: false