name: OhNoez

main: org.selurgniman.bukkit.ohnoez.OhNoez

version: 0.6

database: false

commands:
    ohnoez:
        description: lists the items you dropped at your last death
        usage: /ohnoez [list|credits|claim]